CREATE TABLE IF NOT EXISTS projects(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> ''),
    priority INTEGER NOT NULL,
    description text,
    delivery DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS tasks(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> ''),
    done BOOLEAN,
    projectID INTEGER REFERENCES projects(id)
);

INSERT INTO projects(name, priority, description, delivery) VALUES('Hacer proyecto web', 1, 'Hacerlo temprano', '2019-05-12');

INSERT INTO projects(name, priority, description, delivery) VALUES('Hacer app movil', 4, 'Hacerlo temprano', '2019-06-11');

INSERT INTO projects(name, priority, description, delivery) VALUES('Hacer API', 3, 'Sera el primer paso', '2019-06-11');

/* Insertando a las tasks */
INSERT INTO tasks(name, done, projectID) VALUES('Crear maquetado', false, 1);

INSERT INTO tasks(name, done, projectID) VALUES('Crear estilos', false, 1);

INSERT INTO tasks(name, done, projectID) VALUES('Elegir iOS o Android', false, 2);

INSERT INTO tasks(name, done, projectID) VALUES('Hacer estructura bella', false, 3);
